# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kimen < Formula
  desc "Local-first secrets tool"
  homepage "https://github.com/flakstad/kimen"
  version "2026.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flakstad/kimen/releases/download/v2026.5.0/kimen_2026.5.0_darwin_amd64.tar.gz"
      sha256 "8b1d3b641784820a18ba183a9493bf74d40a7c985afa47c758ca438af177afe3"

      define_method(:install) do
        bin.install "kimen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flakstad/kimen/releases/download/v2026.5.0/kimen_2026.5.0_darwin_arm64.tar.gz"
      sha256 "1a76dab1c605c4b403749c53c5f6016694696258a0b8ca54b9350b2ff6592ca5"

      define_method(:install) do
        bin.install "kimen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flakstad/kimen/releases/download/v2026.5.0/kimen_2026.5.0_linux_amd64.tar.gz"
      sha256 "2385b6b85188817b79376a2798450a14deb746036f733a146c15cb42b9dd3d78"
      define_method(:install) do
        bin.install "kimen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flakstad/kimen/releases/download/v2026.5.0/kimen_2026.5.0_linux_arm64.tar.gz"
      sha256 "23fdd2fdd7471fba8d4ecb3a9b6914718aba8842e52d6b1944ee0abc8591b07c"
      define_method(:install) do
        bin.install "kimen"
      end
    end
  end

  test do
    system "#{bin}/kimen", "version"
  end
end
