# typed: false
# frozen_string_literal: true

# This file was generated by Kimen release CI. DO NOT EDIT.
class Kimen < Formula
  desc "Local-first secrets tool"
  homepage "https://github.com/flakstad/kimen"
  version "2026.6.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flakstad/kimen/releases/download/v2026.6.23/kimen_2026.6.23_darwin_amd64.tar.gz"
      sha256 "f3ee7b4cb68076bfe80a46e675c560d776b6c56e026451cffe6c27ed8b156ede"

      def install
        bin.install "kimen"
      end
    end

    if Hardware::CPU.arm?
      url "https://github.com/flakstad/kimen/releases/download/v2026.6.23/kimen_2026.6.23_darwin_arm64.tar.gz"
      sha256 "ae94ee2ab815d32c803b1dfc9fff3f1428dcbae1bb89e31ebed5eec174a079b4"

      def install
        bin.install "kimen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flakstad/kimen/releases/download/v2026.6.23/kimen_2026.6.23_linux_amd64.tar.gz"
      sha256 "42277f3acb94b6446feb6ca090713e2ac9534a2aa891178fb858d16593d7cd00"

      def install
        bin.install "kimen"
      end
    end

    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flakstad/kimen/releases/download/v2026.6.23/kimen_2026.6.23_linux_arm64.tar.gz"
      sha256 "6c998ecfb88645ee4db8ec1912c35e9087e3c9ea74b96686d715ca51cd74d85f"

      def install
        bin.install "kimen"
      end
    end
  end

  test do
    system "#{bin}/kimen", "version"
  end
end
