# typed: false
# frozen_string_literal: true

# This file was generated by Kimen release CI. DO NOT EDIT.
class Kimen < Formula
  desc "Local-first secrets tool"
  homepage "https://github.com/flakstad/kimen"
  version "2026.6.22"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flakstad/kimen/releases/download/v2026.6.22/kimen_2026.6.22_darwin_amd64.tar.gz"
      sha256 "6520f8a9634ed4790f4f09b786e1ce3b3e9f910a3b80295e06243a4edea4c2ae"

      define_method(:install) do
        bin.install "kimen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flakstad/kimen/releases/download/v2026.6.22/kimen_2026.6.22_darwin_arm64.tar.gz"
      sha256 "1353424d9d633050a6c3f7ba5160a0a0fcbcfc606705a2ac586d634aade20b60"

      define_method(:install) do
        bin.install "kimen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/flakstad/kimen/releases/download/v2026.6.22/kimen_2026.6.22_linux_amd64.tar.gz"
      sha256 "840cca016e57f036b306e017113619bf600d113a2fc595cd701924f96e2f61bc"
      define_method(:install) do
        bin.install "kimen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flakstad/kimen/releases/download/v2026.6.22/kimen_2026.6.22_linux_arm64.tar.gz"
      sha256 "ed4b579891f7ee1f606aad4e9d8df7ac26963baa45eb32af16189c1a0c930053"
      define_method(:install) do
        bin.install "kimen"
      end
    end
  end

  test do
    system "#{bin}/kimen", "version"
  end
end
